// Transformers Index - Auto-generated
// This file is automatically generated by build/build-index.js
// Do not edit manually - run 'npm run build:index' to regenerate

import elder_futhark from './ancient/elder-futhark.js';
import hieroglyphics from './ancient/hieroglyphics.js';
import ogham from './ancient/ogham.js';
import roman_numerals from './ancient/roman-numerals.js';
import alternating_case from './case/alternating-case.js';
import camel_case from './case/camel-case.js';
import kebab_case from './case/kebab-case.js';
import random_case from './case/random-case.js';
import sentence_case from './case/sentence-case.js';
import snake_case from './case/snake-case.js';
import title_case from './case/title-case.js';
import adfgx from './cipher/adfgx.js';
import affine from './cipher/affine.js';
import atbash from './cipher/atbash.js';
import autokey from './cipher/autokey.js';
import baconian from './cipher/baconian.js';
import beaufort from './cipher/beaufort.js';
import bifid from './cipher/bifid.js';
import caesar from './cipher/caesar.js';
import columnar_transposition from './cipher/columnar-transposition.js';
import four_square from './cipher/four-square.js';
import gronsfeld from './cipher/gronsfeld.js';
import hill from './cipher/hill.js';
import homophonic from './cipher/homophonic.js';
import nihilist from './cipher/nihilist.js';
import pigpen from './cipher/pigpen.js';
import playfair from './cipher/playfair.js';
import polybius from './cipher/polybius.js';
import porta from './cipher/porta.js';
import rail_fence from './cipher/rail-fence.js';
import rot128 from './cipher/rot128.js';
import rot13 from './cipher/rot13.js';
import rot18 from './cipher/rot18.js';
import rot47 from './cipher/rot47.js';
import rot5 from './cipher/rot5.js';
import rot8000 from './cipher/rot8000.js';
import scytale from './cipher/scytale.js';
import trifid from './cipher/trifid.js';
import two_square from './cipher/two-square.js';
import vigenere from './cipher/vigenere.js';
import xor from './cipher/xor.js';
import ascii85 from './encoding/ascii85.js';
import base122 from './encoding/base122.js';
import base32 from './encoding/base32.js';
import base36 from './encoding/base36.js';
import base45 from './encoding/base45.js';
import base58 from './encoding/base58.js';
import base62 from './encoding/base62.js';
import base64 from './encoding/base64.js';
import base64url from './encoding/base64url.js';
import base91 from './encoding/base91.js';
import baudot from './encoding/baudot.js';
import bcd from './encoding/bcd.js';
import binary from './encoding/binary.js';
import ebcdic from './encoding/ebcdic.js';
import emoji_encoding from './encoding/emoji-encoding.js';
import gray_code from './encoding/gray-code.js';
import hex from './encoding/hex.js';
import html from './encoding/html.js';
import invisible_text from './encoding/invisible-text.js';
import quoted_printable from './encoding/quoted-printable.js';
import unicode_points from './encoding/unicode-points.js';
import url from './encoding/url.js';
import uuencoding from './encoding/uuencoding.js';
import yenc from './encoding/yenc.js';
import z85 from './encoding/z85.js';
import aurebesh from './fantasy/aurebesh.js';
import dovahzul from './fantasy/dovahzul.js';
import klingon from './fantasy/klingon.js';
import quenya from './fantasy/quenya.js';
import tengwar from './fantasy/tengwar.js';
import bitwise_not from './format/bitwise-not.js';
import boustrophedon from './format/boustrophedon.js';
import capitalize_words from './format/capitalize-words.js';
import indent from './format/indent.js';
import javanais from './format/javanais.js';
import latin_gibberish from './format/latin-gibberish.js';
import leetspeak from './format/leetspeak.js';
import letters_extraction from './format/letters-extraction.js';
import letters_numbers_only from './format/letters-numbers-only.js';
import line_numbers from './format/line-numbers.js';
import louchebem from './format/louchebem.js';
import lowercase_all from './format/lowercase-all.js';
import mirror_digits from './format/mirror-digits.js';
import numbers_only from './format/numbers-only.js';
import pigLatin from './format/pigLatin.js';
import qwerty_shift from './format/qwerty-shift.js';
import remove_accents from './format/remove-accents.js';
import remove_consonants from './format/remove-consonants.js';
import remove_duplicates from './format/remove-duplicates.js';
import remove_extra_spaces from './format/remove-extra-spaces.js';
import remove_html_tags from './format/remove-html-tags.js';
import remove_newlines from './format/remove-newlines.js';
import remove_numbers from './format/remove-numbers.js';
import remove_punctuation from './format/remove-punctuation.js';
import remove_tabs from './format/remove-tabs.js';
import remove_zero_width from './format/remove-zero-width.js';
import reverse_words from './format/reverse-words.js';
import reverse from './format/reverse.js';
import shuffle_characters from './format/shuffle-characters.js';
import shuffle_words from './format/shuffle-words.js';
import spaces_remover from './format/spaces-remover.js';
import text_justify from './format/text-justify.js';
import uppercase_all from './format/uppercase-all.js';
import uppercase_lowercase from './format/uppercase-lowercase.js';
import whitespace_steganography from './format/whitespace-steganography.js';
import word_wrap from './format/word-wrap.js';
import zerowidth_steganography from './format/zerowidth-steganography.js';
import randomizer from './special/randomizer.js';
import a1z26 from './technical/a1z26.js';
import braille from './technical/braille.js';
import brainfuck from './technical/brainfuck.js';
import icao from './technical/icao.js';
import itu from './technical/itu.js';
import maritime_flags from './technical/maritime-flags.js';
import morse from './technical/morse.js';
import nato from './technical/nato.js';
import semaphore from './technical/semaphore.js';
import tap_code from './technical/tap-code.js';
import bold_italic from './unicode/bold-italic.js';
import bold from './unicode/bold.js';
import bubble from './unicode/bubble.js';
import chemical from './unicode/chemical.js';
import circled from './unicode/circled.js';
import cursive from './unicode/cursive.js';
import cyrillic_stylized from './unicode/cyrillic-stylized.js';
import dashed_underline from './unicode/dashed-underline.js';
import dotted_underline from './unicode/dotted-underline.js';
import doubleStruck from './unicode/doubleStruck.js';
import fraktur from './unicode/fraktur.js';
import fullwidth from './unicode/fullwidth.js';
import greek from './unicode/greek.js';
import hiragana from './unicode/hiragana.js';
import italic from './unicode/italic.js';
import katakana from './unicode/katakana.js';
import mathematical from './unicode/mathematical.js';
import medieval from './unicode/medieval.js';
import mirror from './unicode/mirror.js';
import monospace from './unicode/monospace.js';
import negative_squared from './unicode/negative-squared.js';
import overline from './unicode/overline.js';
import parenthesized from './unicode/parenthesized.js';
import regional_indicator from './unicode/regional-indicator.js';
import small_caps from './unicode/small-caps.js';
import squared from './unicode/squared.js';
import strikethrough from './unicode/strikethrough.js';
import subscript from './unicode/subscript.js';
import superscript from './unicode/superscript.js';
import underline from './unicode/underline.js';
import upside_down from './unicode/upside-down.js';
import vaporwave from './unicode/vaporwave.js';
import wavy_underline from './unicode/wavy-underline.js';
import wide_spacing from './unicode/wide-spacing.js';
import wingdings from './unicode/wingdings.js';
import zalgo from './unicode/zalgo.js';
import disemvowel from './visual/disemvowel.js';
import emoji_speak from './visual/emoji-speak.js';
import rovarspraket from './visual/rovarspraket.js';
import ubbi_dubbi from './visual/ubbi-dubbi.js';

// Combine all transforms
const transforms = {
    elder_futhark,
    hieroglyphics,
    ogham,
    roman_numerals,
    alternating_case,
    camel_case,
    kebab_case,
    random_case,
    sentence_case,
    snake_case,
    title_case,
    adfgx,
    affine,
    atbash,
    autokey,
    baconian,
    beaufort,
    bifid,
    caesar,
    columnar_transposition,
    four_square,
    gronsfeld,
    hill,
    homophonic,
    nihilist,
    pigpen,
    playfair,
    polybius,
    porta,
    rail_fence,
    rot128,
    rot13,
    rot18,
    rot47,
    rot5,
    rot8000,
    scytale,
    trifid,
    two_square,
    vigenere,
    xor,
    ascii85,
    base122,
    base32,
    base36,
    base45,
    base58,
    base62,
    base64,
    base64url,
    base91,
    baudot,
    bcd,
    binary,
    ebcdic,
    emoji_encoding,
    gray_code,
    hex,
    html,
    invisible_text,
    quoted_printable,
    unicode_points,
    url,
    uuencoding,
    yenc,
    z85,
    aurebesh,
    dovahzul,
    klingon,
    quenya,
    tengwar,
    bitwise_not,
    boustrophedon,
    capitalize_words,
    indent,
    javanais,
    latin_gibberish,
    leetspeak,
    letters_extraction,
    letters_numbers_only,
    line_numbers,
    louchebem,
    lowercase_all,
    mirror_digits,
    numbers_only,
    pigLatin,
    qwerty_shift,
    remove_accents,
    remove_consonants,
    remove_duplicates,
    remove_extra_spaces,
    remove_html_tags,
    remove_newlines,
    remove_numbers,
    remove_punctuation,
    remove_tabs,
    remove_zero_width,
    reverse_words,
    reverse,
    shuffle_characters,
    shuffle_words,
    spaces_remover,
    text_justify,
    uppercase_all,
    uppercase_lowercase,
    whitespace_steganography,
    word_wrap,
    zerowidth_steganography,
    randomizer,
    a1z26,
    braille,
    brainfuck,
    icao,
    itu,
    maritime_flags,
    morse,
    nato,
    semaphore,
    tap_code,
    bold_italic,
    bold,
    bubble,
    chemical,
    circled,
    cursive,
    cyrillic_stylized,
    dashed_underline,
    dotted_underline,
    doubleStruck,
    fraktur,
    fullwidth,
    greek,
    hiragana,
    italic,
    katakana,
    mathematical,
    medieval,
    mirror,
    monospace,
    negative_squared,
    overline,
    parenthesized,
    regional_indicator,
    small_caps,
    squared,
    strikethrough,
    subscript,
    superscript,
    underline,
    upside_down,
    vaporwave,
    wavy_underline,
    wide_spacing,
    wingdings,
    zalgo,
    disemvowel,
    emoji_speak,
    rovarspraket,
    ubbi_dubbi
};

// Export for both ES6 modules and browser global
export default transforms;

// Also expose as window.transforms for backward compatibility
if (typeof window !== 'undefined') {
    window.transforms = transforms;
    window.encoders = transforms; // alias
}
